package com.mx.apiCinepolis.entity;

import java.io.Serializable;
import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/*
 * ----API REST CINEPOLIS
CREATE TABLE PELICULAS_CINE(
ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
NOMBRE VARCHAR2(80),
FECHA_LANZ DATE,
GENERO VARCHAR2 (80),
PRECIO NUMBER NOT NULL
); 
 * */

//Serializacion: desintegracion en bytes del estado de un objeto
//Deserealizacion: Recontruccion del estado del objeto a partir de los bytes
//implementando metodos de una interfase

@Entity
@Table(name = "PELICULAS_CINE")
@NoArgsConstructor
@AllArgsConstructor
@Data

public class Peliculas implements Serializable {

	// Es una variable que no puede ser modificada
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) // Se agrega cuando tenemos autoincrementable
	@Column(name = "ID")
	private Long idPeli;
	@Column(name = "NOMBRE")
	private String nombre;
	@Column(name = "FECHA_LANZ")
	private Date fechaLanz;
	@Column(name = "GENERO")
	private String genero;
	@Column(name = "PRECIO")
	private float precio;

}
